from main import db

class ProdItens(db.Model):
    __bind_key__ = 'product'  # SQLAlchemy to use the 'product' bind
    __tablename__ = "prod_itens"

    prod_itens_id = db.Column(db.Integer, primary_key=True)
    produtos_id_fk = db.Column(db.Integer, primary_key=False)
    instit_id_fk = db.Column(db.Integer, primary_key=False)
    instit_matriz_id_fk = db.Column(db.Integer, primary_key=False)
    codprod = db.Column(db.Integer, primary_key=False)
    ativo = db.Column(db.Integer, primary_key=False)
    bxest = db.Column(db.Integer, primary_key=False)
    est_minimo = db.Column(db.Numeric, primary_key=False)
    est_fiscal = db.Column(db.Numeric, primary_key=False)
    est_frente = db.Column(db.Numeric, primary_key=False)
    est_dep1 = db.Column(db.Numeric, primary_key=False)
    est_dep2 = db.Column(db.Numeric, primary_key=False)
    est_dep3 = db.Column(db.Numeric, primary_key=False)
    compra = db.Column(db.Numeric, primary_key=False)
    frete = db.Column(db.Numeric, primary_key=False)
    ipi = db.Column(db.Numeric, primary_key=False)
    aliq = db.Column(db.Integer, primary_key=False)
    custo = db.Column(db.Numeric, primary_key=False)
    lucro = db.Column(db.Numeric, primary_key=False)
    prvenda1 = db.Column(db.Numeric, primary_key=False)
    prvenda2 = db.Column(db.Numeric, primary_key=False)
    prvenda3 = db.Column(db.Numeric, primary_key=False)
    prvenda4 = db.Column(db.Numeric, primary_key=False)
    prvenda5 = db.Column(db.Numeric, primary_key=False)
    locavel = db.Column(db.Integer, primary_key=False)
    prloc = db.Column(db.Numeric, primary_key=False)
    vdatac = db.Column(db.Integer, primary_key=False)
    qtdatac = db.Column(db.Numeric, primary_key=False)
    pratac = db.Column(db.Numeric, primary_key=False)
    loc_frente = db.Column(db.String, primary_key=False)
    loc_dep1 = db.Column(db.String, primary_key=False)
    loc_dep2 = db.Column(db.String, primary_key=False)
    loc_dep3 = db.Column(db.String, primary_key=False)
    comissao_atv = db.Column(db.Integer, primary_key=False)
    comissao_val = db.Column(db.Numeric, primary_key=False)
    produtos_id_combo = db.Column(db.Integer, primary_key=False)
    qtd_combo = db.Column(db.Numeric, primary_key=False)
