"""personNatural

Revision ID: 764ed3109d41
Revises: 
Create Date: 2025-11-16 17:07:09.083429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '764ed3109d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pesfis', schema=None) as batch_op:
        batch_op.alter_column('emprend',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=60),
               comment=None,
               existing_comment='endereço empresa',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('orendas',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=60),
               comment=None,
               existing_comment='descr outras rendas',
               existing_nullable=True)
        batch_op.alter_column('vrendas',
               existing_type=mysql.DECIMAL(unsigned=True, precision=10, scale=2),
               comment=None,
               existing_comment='valor outras rendas',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('irpf',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='decla IRPF 0=não 1=sim',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('depend',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='num.dependentes',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('conjuge',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cpfconj',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=25),
               existing_nullable=True)
        batch_op.alter_column('profconj',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('emprconj',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='empresa trab conjuge',
               existing_nullable=True)
        batch_op.alter_column('telconj',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('mailconj',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idpescod'))
        batch_op.drop_index(batch_op.f('idpesfis'))
        batch_op.create_foreign_key(None, 'pescod', ['pescod_id_fk'], ['pescod_id'])
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('naturalidade_id_fk')

    with op.batch_alter_table('pesjur', schema=None) as batch_op:
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment=None,
               existing_comment='tipo empresarial',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('tribut',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               nullable=True,
               comment=None,
               existing_comment='1=contr ICMS 2=isento 9=n trib',
               existing_server_default=sa.text('1'))
        batch_op.alter_column('data_abertura',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idpescod'))
        batch_op.create_foreign_key(None, 'pescod', ['pescod_id_fk'], ['pescod_id'])
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('data_atualizacao')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('instit_matriz_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='id tabela instit',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ativo',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               comment=None,
               existing_comment='1=não 2=sim',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('codprod',
               existing_type=mysql.INTEGER(display_width=7, unsigned=True),
               comment=None,
               existing_comment='cod prod único na instit',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tam',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment=None,
               existing_comment='comprimento(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('larg',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment=None,
               existing_comment='largura(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('alt',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment=None,
               existing_comment='largura(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('cest',
               existing_type=mysql.VARCHAR(length=8),
               comment=None,
               existing_comment='cod subst tribut',
               existing_nullable=True)
        batch_op.alter_column('desnf',
               existing_type=mysql.VARCHAR(length=40),
               comment=None,
               existing_comment='descricao tributaria',
               existing_nullable=False,
               existing_server_default=sa.text("'informe a descricao trib do produto'"))
        batch_op.alter_column('combo',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True),
               comment=None,
               existing_comment='jamais pode ser alterado, 0=não 1=é um combo de itens',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('img_bites',
               existing_type=mysql.INTEGER(display_width=6, unsigned=True),
               comment=None,
               existing_comment='tam arq img (bites)',
               existing_nullable=True,
               existing_server_default=sa.text('8878'))
        batch_op.alter_column('datatz',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('id_matriz'))
        batch_op.drop_index(batch_op.f('id_matriz_2'))
        batch_op.drop_index(batch_op.f('matriz'))
        batch_op.create_unique_constraint('codbarra', ['instit_matriz_id_fk', 'codbarra'])
        batch_op.create_unique_constraint('codprod', ['instit_matriz_id_fk', 'codprod'])
        batch_op.create_unique_constraint('descr', ['instit_matriz_id_fk', 'descr'])
        batch_op.drop_table_comment(
        existing_comment='InnoDB free: 11264 kB; InnoDB free: 11264 kB; InnoDB free: 1'
    )
        batch_op.drop_column('usuatz')

    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal', sa.Integer(), nullable=True))
        batch_op.alter_column('situacao',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               nullable=True,
               comment=None,
               existing_comment='1 = ativo / 0 = inativo',
               existing_server_default=sa.text('1'))
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('data'))
        batch_op.create_foreign_key(None, 'pescod', ['pescod_id_fk'], ['pescod_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_uid', sa.String(length=50), nullable=True))
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('instit_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ativo',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               nullable=True,
               comment=None,
               existing_comment='0=não 1=sim',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('users_grp_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('login',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('numlog',
               existing_type=mysql.INTEGER(display_width=6, unsigned=True),
               nullable=True,
               comment=None,
               existing_comment='total de logins',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('acess',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='1=permitido 0ou2=nao',
               existing_server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"))
        batch_op.alter_column('desenv',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               nullable=True,
               comment=None,
               existing_comment='0:nao 1=desenvolvedor',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('data_senha',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('data_criacao',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('data_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.drop_index(batch_op.f('id'))
        batch_op.drop_index(batch_op.f('login'))

    with op.batch_alter_table('users_grp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_grp_uid', sa.Integer(), nullable=False))
        batch_op.alter_column('nome_grupo',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('instit_id_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('acess',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True,
               comment=None,
               existing_comment='1=permitido 0ou2=nao',
               existing_server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"))
        batch_op.drop_index(batch_op.f('instit'))
        batch_op.drop_column('users_grp_id')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_grp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_grp_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.create_index(batch_op.f('instit'), ['instit_id_fk', 'nome_grupo'], unique=True)
        batch_op.alter_column('acess',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False,
               comment='1=permitido 0ou2=nao',
               existing_server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"))
        batch_op.alter_column('instit_id_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('nome_grupo',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_column('users_grp_uid')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('id'), ['instit_id_fk', 'pescod_id_fk'], unique=False)
        batch_op.alter_column('data_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('data_criacao',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('data_senha',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
        batch_op.alter_column('desenv',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               nullable=False,
               comment='0:nao 1=desenvolvedor',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('acess',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment='1=permitido 0ou2=nao',
               existing_server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"))
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('numlog',
               existing_type=mysql.INTEGER(display_width=6, unsigned=True),
               nullable=False,
               comment='total de logins',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('login',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('users_grp_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ativo',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               nullable=False,
               comment='0=não 1=sim',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('instit_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('users_uid')

    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('data'), ['data_criacao'], unique=False)
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('situacao',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               nullable=False,
               comment='1 = ativo / 0 = inativo',
               existing_server_default=sa.text('1'))
        batch_op.drop_column('principal')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuatz', mysql.INTEGER(display_width=5, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        'InnoDB free: 11264 kB; InnoDB free: 11264 kB; InnoDB free: 1',
        existing_comment=None
    )
        batch_op.drop_constraint('descr', type_='unique')
        batch_op.drop_constraint('codprod', type_='unique')
        batch_op.drop_constraint('codbarra', type_='unique')
        batch_op.create_index(batch_op.f('matriz'), ['instit_matriz_id_fk', 'codprod'], unique=True)
        batch_op.create_index(batch_op.f('id_matriz_2'), ['instit_matriz_id_fk', 'codbarra'], unique=True)
        batch_op.create_index(batch_op.f('id_matriz'), ['instit_matriz_id_fk', 'descr'], unique=True)
        batch_op.alter_column('datatz',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('img_bites',
               existing_type=mysql.INTEGER(display_width=6, unsigned=True),
               comment='tam arq img (bites)',
               existing_nullable=True,
               existing_server_default=sa.text('8878'))
        batch_op.alter_column('combo',
               existing_type=mysql.INTEGER(display_width=3, unsigned=True),
               comment='jamais pode ser alterado, 0=não 1=é um combo de itens',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('desnf',
               existing_type=mysql.VARCHAR(length=40),
               comment='descricao tributaria',
               existing_nullable=False,
               existing_server_default=sa.text("'informe a descricao trib do produto'"))
        batch_op.alter_column('cest',
               existing_type=mysql.VARCHAR(length=8),
               comment='cod subst tribut',
               existing_nullable=True)
        batch_op.alter_column('alt',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment='largura(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('larg',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment='largura(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('tam',
               existing_type=mysql.DECIMAL(unsigned=True, precision=6, scale=3),
               comment='comprimento(m)',
               existing_nullable=False,
               existing_server_default=sa.text('0.000'))
        batch_op.alter_column('codprod',
               existing_type=mysql.INTEGER(display_width=7, unsigned=True),
               comment='cod prod único na instit',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ativo',
               existing_type=mysql.INTEGER(display_width=1, unsigned=True),
               comment='1=não 2=sim',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('instit_matriz_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='id tabela instit',
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pesjur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
        batch_op.add_column(sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idpescod'), ['pescod_id_fk'], unique=False)
        batch_op.alter_column('data_abertura',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('tribut',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               nullable=False,
               comment='1=contr ICMS 2=isento 9=n trib',
               existing_server_default=sa.text('1'))
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(display_width=2, unsigned=True),
               comment='tipo empresarial',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('pescod_id_fk',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pesfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naturalidade_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='municipios id fk'))
        batch_op.add_column(sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', mysql.TIMESTAMP(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idpesfis'), ['pesfis_id'], unique=False)
        batch_op.create_index(batch_op.f('idpescod'), ['pescod_id_fk'], unique=False)
        batch_op.alter_column('mailconj',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('telconj',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('emprconj',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               comment='empresa trab conjuge',
               existing_nullable=True)
        batch_op.alter_column('profconj',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('cpfconj',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=True)
        batch_op.alter_column('conjuge',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('depend',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='num.dependentes',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('irpf',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='decla IRPF 0=não 1=sim',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('vrendas',
               existing_type=mysql.DECIMAL(unsigned=True, precision=10, scale=2),
               comment='valor outras rendas',
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('orendas',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=50),
               comment='descr outras rendas',
               existing_nullable=True)
        batch_op.alter_column('emprend',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=200),
               comment='endereço empresa',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def upgrade_sales():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prod_itens',
    sa.Column('prod_itens_id', sa.Integer(), nullable=False),
    sa.Column('produtos_id_fk', sa.Integer(), nullable=False),
    sa.Column('instit_id_fk', sa.Integer(), nullable=False),
    sa.Column('instit_matriz_id_fk', sa.Integer(), nullable=False),
    sa.Column('codprod', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('bxest', sa.Integer(), nullable=False),
    sa.Column('est_minimo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('est_fiscal', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('est_frente', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('est_dep1', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('est_dep2', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('est_dep3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ipi', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aliq', sa.Integer(), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lucro', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prvenda1', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prvenda2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prvenda3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prvenda4', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prvenda5', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('locavel', sa.Integer(), nullable=False),
    sa.Column('prloc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vdatac', sa.Integer(), nullable=False),
    sa.Column('qtdatac', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('pratac', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loc_frente', sa.String(length=50), nullable=True),
    sa.Column('loc_dep1', sa.String(length=50), nullable=True),
    sa.Column('loc_dep2', sa.String(length=50), nullable=True),
    sa.Column('loc_dep3', sa.String(length=50), nullable=True),
    sa.Column('comissao_atv', sa.Integer(), nullable=False),
    sa.Column('comissao_val', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('produtos_id_combo', sa.Integer(), nullable=True),
    sa.Column('qtd_combo', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('prod_itens_id')
    )
    with op.batch_alter_table('pesfis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idpescod'))
        batch_op.drop_index(batch_op.f('idpesfis'))

    op.drop_table('pesfis')
    op.drop_table('pescod')
    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('data'))

    op.drop_table('telefones')
    op.drop_table('acl_role_permissions')
    with op.batch_alter_table('users_grp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('instit'))

    op.drop_table('users_grp')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id_matriz'))
        batch_op.drop_index(batch_op.f('id_matriz_2'))
        batch_op.drop_index(batch_op.f('matriz'))

    op.drop_table('produtos')
    op.drop_table('person_pronouns')
    op.drop_table('logradouros')
    op.drop_table('instit')
    op.drop_table('paises')
    with op.batch_alter_table('acl_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('acl_roles')
    op.drop_table('enderecos')
    with op.batch_alter_table('acl_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('acl_permissions')
    op.drop_table('municipios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))
        batch_op.drop_index(batch_op.f('login'))

    op.drop_table('users')
    op.drop_table('mails')
    with op.batch_alter_table('pesjur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idpescod'))

    op.drop_table('pesjur')
    # ### end Alembic commands ###


def downgrade_sales():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesjur',
    sa.Column('pesjur_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fantasia', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ramo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('inscricao_estadual', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('inscricao_municipal', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='tipo empresarial'),
    sa.Column('capsocial', mysql.DECIMAL(unsigned=True, precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('faturamento', mysql.DECIMAL(unsigned=True, precision=15, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('tribut', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='1=contr ICMS 2=isento 9=n trib'),
    sa.Column('contato', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('data_abertura', sa.DATE(), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.PrimaryKeyConstraint('pesjur_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('pesjur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idpescod'), ['pescod_id_fk'], unique=False)

    op.create_table('mails',
    sa.Column('mails_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('situacao', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='Email address'),
    sa.Column('data_criacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('principal', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('mails_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('users',
    sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('instit_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('ativo', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='0=não 1=sim'),
    sa.Column('users_grp_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=25), server_default=sa.text("''"), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('numlog', mysql.INTEGER(display_width=6, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='total de logins'),
    sa.Column('senha', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('acess', mysql.VARCHAR(length=255), server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"), nullable=False, comment='1=permitido 0ou2=nao'),
    sa.Column('desenv', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='0:nao 1=desenvolvedor'),
    sa.Column('data_senha', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.PrimaryKeyConstraint('users_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('id'), ['instit_id_fk', 'pescod_id_fk'], unique=False)

    op.create_table('municipios',
    sa.Column('municipios_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='Name of the city'),
    sa.Column('cid_ibge', mysql.INTEGER(display_width=7, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='IBGE code of the city'),
    sa.Column('ufs_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Foreign key to the state table'),
    sa.Column('wikidata_id', mysql.VARCHAR(length=15), nullable=True, comment='Wikidata ID for the city'),
    sa.PrimaryKeyConstraint('municipios_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('acl_permissions',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('acl_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('enderecos',
    sa.Column('enderecos_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('situacao', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='1 = ativo 0 = inativo'),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('logradouros_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='tipo logradouro'),
    sa.Column('logradouro', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('municipios_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1827'), autoincrement=False, nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('principal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Indicates if this is the main address for the person'),
    sa.Column('apelido', mysql.VARCHAR(length=50), nullable=True, comment='Label for the address, e.g., "Home", "Office"'),
    sa.Column('codigo_ibge_municipio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=60), nullable=True, comment='City name'),
    sa.Column('state', mysql.VARCHAR(length=50), nullable=True, comment='State abbreviation'),
    sa.Column('country', mysql.VARCHAR(length=3), nullable=True, comment='Country name'),
    sa.PrimaryKeyConstraint('enderecos_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('acl_roles',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('acl_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('paises',
    sa.Column('id_paises', mysql.INTEGER(display_width=3, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cod_bcb', mysql.INTEGER(display_width=4, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trib_fav_bcb', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('iso2Code', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('iso3Code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('m49Code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('phoneCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('enUs', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('esEs', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_paises'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('instit',
    sa.Column('instit_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('instit_matriz_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ativo', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('slogan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('modulos', mysql.VARCHAR(length=100), server_default=sa.text("'0'"), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('site', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=True),
    sa.Column('data_atualizacao', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('instit_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('logradouros',
    sa.Column('Id', mysql.INTEGER(display_width=2), autoincrement=True, nullable=False),
    sa.Column('logr', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('abrev', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('person_pronouns',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pt_BR', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('produtos',
    sa.Column('produtos_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('instit_matriz_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='id tabela instit'),
    sa.Column('codprod', mysql.INTEGER(display_width=7, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='cod prod único na instit'),
    sa.Column('ativo', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='1=não 2=sim'),
    sa.Column('descr', mysql.VARCHAR(length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('descres', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('und', mysql.INTEGER(display_width=2), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('prod_grp_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('prod_grp_nv1id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('prod_grp_nv2id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('tam', mysql.DECIMAL(unsigned=True, precision=6, scale=3), server_default=sa.text('0.000'), nullable=False, comment='comprimento(m)'),
    sa.Column('larg', mysql.DECIMAL(unsigned=True, precision=6, scale=3), server_default=sa.text('0.000'), nullable=False, comment='largura(m)'),
    sa.Column('alt', mysql.DECIMAL(unsigned=True, precision=6, scale=3), server_default=sa.text('0.000'), nullable=False, comment='largura(m)'),
    sa.Column('cubag', mysql.DECIMAL(unsigned=True, precision=7, scale=4), server_default=sa.text('0.0000'), nullable=False),
    sa.Column('peso', mysql.DECIMAL(unsigned=True, precision=10, scale=2), nullable=True),
    sa.Column('codbarra', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('fabr_id_fk', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('forn_pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('caract', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ncm', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('cest', mysql.VARCHAR(length=8), nullable=True, comment='cod subst tribut'),
    sa.Column('desnf', mysql.VARCHAR(length=40), server_default=sa.text("'informe a descricao trib do produto'"), nullable=False, comment='descricao tributaria'),
    sa.Column('combo', mysql.INTEGER(display_width=3, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='jamais pode ser alterado, 0=não 1=é um combo de itens'),
    sa.Column('foto', mysql.VARCHAR(length=25), server_default=sa.text("'nofoto.gif'"), nullable=False),
    sa.Column('img_bites', mysql.INTEGER(display_width=6, unsigned=True), server_default=sa.text('8878'), autoincrement=False, nullable=True, comment='tam arq img (bites)'),
    sa.Column('datatz', mysql.DATETIME(), nullable=True),
    sa.Column('usuatz', mysql.INTEGER(display_width=5, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('produtos_id'),
    comment='InnoDB free: 11264 kB; InnoDB free: 11264 kB; InnoDB free: 1',
    mysql_collate='latin1_swedish_ci',
    mysql_comment='InnoDB free: 11264 kB; InnoDB free: 11264 kB; InnoDB free: 1',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('matriz'), ['instit_matriz_id_fk', 'codprod'], unique=True)
        batch_op.create_index(batch_op.f('id_matriz_2'), ['instit_matriz_id_fk', 'codbarra'], unique=True)
        batch_op.create_index(batch_op.f('id_matriz'), ['instit_matriz_id_fk', 'descr'], unique=True)

    op.create_table('users_grp',
    sa.Column('users_grp_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_grupo', mysql.VARCHAR(length=15), server_default=sa.text("''"), nullable=False),
    sa.Column('instit_id_fk', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('acess', mysql.VARCHAR(length=255), server_default=sa.text("'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'"), nullable=False, comment='1=permitido 0ou2=nao'),
    sa.Column('data_criacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('users_grp_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('users_grp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('instit'), ['instit_id_fk', 'nome_grupo'], unique=True)

    op.create_table('acl_role_permissions',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['acl_permissions.uid'], name=op.f('acl_role_permissions_ibfk_1')),
    sa.ForeignKeyConstraint(['role_id'], ['acl_roles.uid'], name=op.f('acl_role_permissions_ibfk_2')),
    sa.PrimaryKeyConstraint('uid', 'role_id', 'permission_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('telefones',
    sa.Column('telefones_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('situacao', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='1 = ativo / 0 = inativo'),
    sa.Column('tel', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('telefones_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('telefones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('data'), ['data_criacao'], unique=False)

    op.create_table('pescod',
    sa.Column('pescod_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('instit_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sit', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.Column('forn', mysql.INTEGER(display_width=1, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('cpfcnpj', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('nomeOrRazaoSocial', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=100), server_default=sa.text("'nofoto.gif'"), nullable=True),
    sa.Column('img_bites', mysql.INTEGER(display_width=6, unsigned=True), server_default=sa.text('8878'), autoincrement=False, nullable=True),
    sa.Column('limite', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('saldo', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text("'2000-01-01 00:00:00'"), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), server_default=sa.text("'2000-01-01 00:00:00'"), nullable=True),
    sa.PrimaryKeyConstraint('pescod_id'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('pesfis',
    sa.Column('pesfis_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pescod_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('identidade', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('emissor_identidade', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('naturalidade_id_fk', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='municipios id fk'),
    sa.Column('data_de_nascimento', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('tratam', mysql.INTEGER(display_width=2, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('apelido', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('sexo', mysql.INTEGER(display_width=11), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('pai', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mae', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('profissao', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('ctps', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('salario', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('empresa', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('resp', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cnpj', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('iest', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('imun', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('emprend', mysql.VARCHAR(length=200), server_default=sa.text("'1'"), nullable=True, comment='endereço empresa'),
    sa.Column('orendas', mysql.VARCHAR(length=50), nullable=True, comment='descr outras rendas'),
    sa.Column('vrendas', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text('0.00'), nullable=True, comment='valor outras rendas'),
    sa.Column('irpf', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='decla IRPF 0=não 1=sim'),
    sa.Column('estcivil', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('depend', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='num.dependentes'),
    sa.Column('pensao', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('conjuge', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('cpfconj', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('profconj', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('emprconj', mysql.VARCHAR(length=50), nullable=True, comment='empresa trab conjuge'),
    sa.Column('rendaconj', mysql.DECIMAL(unsigned=True, precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('telconj', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('mailconj', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('birth_country', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('birth_city', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('pesfis_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pesfis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idpesfis'), ['pesfis_id'], unique=False)
        batch_op.create_index(batch_op.f('idpescod'), ['pescod_id_fk'], unique=False)

    op.drop_table('prod_itens')
    # ### end Alembic commands ###

