INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ALLEY', '{\"ALLEE\", \"ALLEY\", \"ALLY\", \"ALY\"}', 'ALY', 'Viela', 'VLA');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ANEX', '{\"ANEX\", \"ANNEX\", \"ANNX\", \"ANX\"}', 'ANX', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ARCADE', '{\"ARC\", \"ARCADE\"}', 'ARC', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('AVENUE', '{\"AV\", \"AVE\", \"AVEN\", \"AVENU\", \"AVENUE\", \"AVN\", \"AVNUE\"}', 'AVE', 'Avenida', 'AV');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BAYOU', '{\"BAYOO\", \"BAYOU\"}', 'BYU', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BEACH', '{\"BCH\", \"BEACH\"}', 'BCH', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BEND', '{\"BEND\", \"BND\"}', 'BND', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BLUFF', '{\"BLF\", \"BLUF\", \"BLUFF\"}', 'BLF', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BLUFFS', '{\"BLUFFS\"}', 'BLFS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BOTTOM', '{\"BOT\", \"BTM\", \"BOTTM\", \"BOTTOM\"}', 'BTM', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BOULEVARD', '{\"BLVD\", \"BOUL\", \"BOULEVARD\", \"BOULV\"}', 'BLVD', 'Boulevard', 'BVD');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BRANCH', '{\"BR\", \"BRNCH\", \"BRANCH\"}', 'BR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BRIDGE', '{\"BRDGE\", \"BRG\", \"BRIDGE\"}', 'BRG', 'Ponte', 'PNT');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BROOK', '{\"BRK\", \"BROOK\"}', 'BRK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BROOKS', '{\"BROOKS\"}', 'BRKS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BURG', '{\"BURG\"}', 'BG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BURGS', '{\"BURGS\"}', 'BGS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('BYPASS', '{\"BYP\", \"BYPA\", \"BYPAS\", \"BYPASS\", \"BYPS\"}', 'BYP', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CAMP', '{\"CAMP\", \"CP\", \"CMP\"}', 'CP', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CANYON', '{\"CANYN\", \"CANYON\", \"CNYN\"}', 'CYN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CAPE', '{\"CAPE\", \"CPE\"}', 'CPE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CAUSEWAY', '{\"CAUSEWAY\", \"CAUSWA\", \"CSWY\"}', 'CSWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CENTER', '{\"CEN\", \"CENT\", \"CENTER\", \"CENTR\", \"CENTRE\", \"CNTER\", \"CNTR\", \"CTR\"}', 'CTR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CENTERS', '{\"CENTERS\"}', 'CTRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CIRCLE', '{\"CIR\", \"CIRC\", \"CIRCL\", \"CIRCLE\", \"CRCL\", \"CRCLE\"}', 'CIR', 'Circular', 'CIR');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CIRCLES', '{\"CIRCLES\"}', 'CIRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CLIFF', '{\"CLF\", \"CLIFF\"}', 'CLF', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CLIFFS', '{\"CLFS\", \"CLIFFS\"}', 'CLFS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CLUB', '{\"CLB\", \"CLUB\"}', 'CLB', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COMMON', '{\"COMMON\"}', 'CMN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COMMONS', '{\"COMMONS\"}', 'CMNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CORNER', '{\"COR\", \"CORNER\"}', 'COR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CORNERS', '{\"CORNERS\", \"CORS\"}', 'CORS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COURSE', '{\"COURSE\", \"CRSE\"}', 'CRSE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COURT', '{\"COURT\", \"CT\"}', 'CT', 'Pátio', 'PAT');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COURTS', '{\"COURTS\", \"CTS\"}', 'CTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COVE', '{\"COVE\", \"CV\"}', 'CV', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('COVES', '{\"COVES\"}', 'CVS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CREEK', '{\"CREEK\", \"CRK\"}', 'CRK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CRESCENT', '{\"CRESCENT\", \"CRES\", \"CRSENT\", \"CRSNT\"}', 'CRES', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CREST', '{\"CREST\"}', 'CRST', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CROSSING', '{\"CROSSING\", \"CRSSNG\", \"XING\"}', 'XING', 'Passarela', 'PSRL');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CROSSROAD', '{\"CROSSROAD\"}', 'XRD', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CROSSROADS', '{\"CROSSROADS\"}', 'XRDS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('CURVE', '{\"CURVE\"}', 'CURV', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('DALE', '{\"DALE\", \"DL\"}', 'DL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('DAM', '{\"DAM\", \"DM\"}', 'DM', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('DIVIDE', '{\"DIV\", \"DIVIDE\", \"DV\", \"DVD\"}', 'DV', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('DRIVE', '{\"DR\", \"DRIV\", \"DRIVE\", \"DRV\"}', 'DR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('DRIVES', '{\"DRIVES\"}', 'DRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ESTATE', '{\"EST\", \"ESTATE\"}', 'EST', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ESTATES', '{\"ESTATES\", \"ESTS\"}', 'ESTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('EXPRESSWAY', '{\"EXP\", \"EXPR\", \"EXPRESS\", \"EXPRESSWAY\", \"EXPW\", \"EXPY\"}', 'EXPY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('EXTENSION', '{\"EXT\", \"EXTENSION\", \"EXTN\", \"EXTNSN\"}', 'EXT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('EXTENSIONS', '{\"EXTS\"}', 'EXTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FALL', '{\"FALL\"}', 'FALL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FALLS', '{\"FALLS\", \"FLS\"}', 'FLS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FERRY', '{\"FERRY\", \"FRRY\", \"FRY\"}', 'FRY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FIELD', '{\"FIELD\", \"FLD\"}', 'FLD', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FIELDS', '{\"FIELDS\", \"FLDS\"}', 'FLDS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FLAT', '{\"FLAT\", \"FLT\"}', 'FLT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FLATS', '{\"FLATS\", \"FLTS\"}', 'FLTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORD', '{\"FORD\", \"FRD\"}', 'FRD', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORDS', '{\"FORDS\"}', 'FRDS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FOREST', '{\"FOREST\", \"FORESTS\", \"FRST\"}', 'FRST', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORGE', '{\"FORG\", \"FORGE\", \"FRG\"}', 'FRG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORGES', '{\"FORGES\"}', 'FRGS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORK', '{\"FORK\", \"FRK\"}', 'FRK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORKS', '{\"FORKS\", \"FRKS\"}', 'FRKS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FORT', '{\"FORT\", \"FRT\", \"FT\"}', 'FT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('FREEWAY', '{\"FREEWAY\", \"FREEWY\", \"FRWAY\", \"FRWY\", \"FWY\"}', 'FWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GARDEN', '{\"GARDEN\", \"GARDN\", \"GRDEN\", \"GRDN\"}', 'GDN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GARDENS', '{\"GARDENS\", \"GDNS\", \"GRDNS\"}', 'GDNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GATEWAY', '{\"GATEWAY\", \"GATEWY\", \"GATWAY\", \"GTWAY\", \"GTWY\"}', 'GTWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GLEN', '{\"GLEN\", \"GLN\"}', 'GLN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GLENS', '{\"GLENS\"}', 'GLNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GREEN', '{\"GREEN\", \"GRN\"}', 'GRN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GREENS', '{\"GREENS\"}', 'GRNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GROVE', '{\"GROV\", \"GROVE\", \"GRV\"}', 'GRV', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('GROVES', '{\"GROVES\"}', 'GRVS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HARBOR', '{\"HARB\", \"HARBOR\", \"HARBR\", \"HBR\", \"HRBOR\"}', 'HBR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HARBORS', '{\"HARBORS\"}', 'HBRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HAVEN', '{\"HAVEN\", \"HVN\"}', 'HVN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HEIGHTS', '{\"HT\", \"HTS\"}', 'HTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HIGHWAY', '{\"HIGHWAY\", \"HIGHWY\", \"HIWAY\", \"HIWY\", \"HWAY\", \"HWY\"}', 'HWY', 'Rodovia', 'ROD');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HILL', '{\"HILL\", \"HL\"}', 'HL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HILLS', '{\"HILLS\", \"HLS\"}', 'HLS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('HOLLOW', '{\"HLLW\", \"HOLLOW\", \"HOLLOWS\", \"HOLW\", \"HOLWS\"}', 'HOLW', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('INLET', '{\"INLT\"}', 'INLT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ISLAND', '{\"IS\", \"ISLAND\", \"ISLND\"}', 'IS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ISLANDS', '{\"ISLANDS\", \"ISLNDS\", \"ISS\"}', 'ISS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ISLE', '{\"ISLE\", \"ISLES\"}', 'ISLE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('JUNCTION', '{\"JCT\", \"JCTION\", \"JCTN\", \"JUNCTION\", \"JUNCTN\", \"JUNCTON\"}', 'JCT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('JUNCTIONS', '{\"JCTNS\", \"JCTS\", \"JUNCTIONS\"}', 'JCTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('KEY', '{\"KEY\", \"KY\"}', 'KY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('KEYS', '{\"KEYS\", \"KYS\"}', 'KYS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('KNOLL', '{\"KNL\", \"KNOL\", \"KNOLL\"}', 'KNL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('KNOLLS', '{\"KNLS\", \"KNOLLS\"}', 'KNLS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LAKE', '{\"LK\", \"LAKE\"}', 'LK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LAKES', '{\"LKS\", \"LAKES\"}', 'LKS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LAND', '{\"LAND\"}', 'LAND', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LANDING', '{\"LANDING\", \"LNDG\", \"LNDNG\"}', 'LNDG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LANE', '{\"LANE\", \"LN\"}', 'LN', 'Travessa', 'TV');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LIGHT', '{\"LGT\", \"LIGHT\"}', 'LGT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LIGHTS', '{\"LIGHTS\"}', 'LGTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LOAF', '{\"LF\", \"LOAF\"}', 'LF', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LOCK', '{\"LCK\", \"LOCK\"}', 'LCK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LOCKS', '{\"LCKS\", \"LOCKS\"}', 'LCKS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LODGE', '{\"LDG\", \"LDGE\", \"LODG\", \"LODGE\"}', 'LDG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('LOOP', '{\"LOOP\", \"LOOPS\"}', 'LOOP', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MALL', '{\"MALL\"}', 'MALL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MANOR', '{\"MNR\", \"MANOR\"}', 'MNR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MANORS', '{\"MANORS\", \"MNRS\"}', 'MNRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MEADOW', '{\"MEADOW\"}', 'MDW', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MEADOWS', '{\"MDW\", \"MDWS\", \"MEADOWS\", \"MEDOWS\"}', 'MDWS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MEWS', '{\"MEWS\"}', 'MEWS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MILL', '{\"MILL\"}', 'ML', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MILLS', '{\"MILLS\"}', 'MLS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MISSION', '{\"MISSN\", \"MSSN\"}', 'MSN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MOTORWAY', '{\"MOTORWAY\"}', 'MTWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MOUNT', '{\"MNT\", \"MT\", \"MOUNT\"}', 'MT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MOUNTAIN', '{\"MNTAIN\", \"MNTN\", \"MOUNTAIN\", \"MOUNTIN\", \"MTIN\", \"MTN\"}', 'MTN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('MOUNTAINS', '{\"MNTNS\", \"MOUNTAINS\"}', 'MTNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('NECK', '{\"NCK\", \"NECK\"}', 'NCK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ORCHARD', '{\"ORCH\", \"ORCHARD\", \"ORCHRD\"}', 'ORCH', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('OTHER', '{\"OTH\",\"OTHR\"}', 'OTH', 'OUTRO', 'OTR');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('OVAL', '{\"OVAL\", \"OVL\"}', 'OVAL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('OVERPASS', '{\"OVERPASS\"}', 'OPAS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PARK', '{\"PARK\", \"PRK\"}', 'PARK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PARKS', '{\"PARKS\"}', 'PARKS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PARKWAY', '{\"PARKWAY\", \"PARKWY\", \"PKWAY\", \"PKWY\", \"PKY\", \"PARKWAYS\", \"PKWYS\"}', 'PKWY', 'Via', 'VIA');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PASS', '{\"PASS\"}', 'PASS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PASSAGE', '{\"PASSAGE\"}', 'PSGE', 'Passagem', 'PSG');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PATH', '{\"PATH\", \"PATHS\"}', 'PATH', 'Caminho', 'CAM');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PIKE', '{\"PIKE\", \"PIKES\"}', 'PIKE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PINE', '{\"PINE\", \"PINES\", \"PNES\"}', 'PNE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PLACE', '{\"PL\"}', 'PL', 'Praça', 'PÇ');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PLAIN', '{\"PLAIN\", \"PLN\"}', 'PLN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PLAINS', '{\"PLAINS\", \"PLNS\"}', 'PLNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PLAZA', '{\"PLAZA\", \"PLZ\", \"PLZA\"}', 'PLZ', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('POINT', '{\"POINT\", \"PT\"}', 'PT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('POINTS', '{\"POINTS\", \"PTS\"}', 'PTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PORT', '{\"PORT\", \"PRT\"}', 'PRT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PORTS', '{\"PORTS\", \"PRTS\"}', 'PRTS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('PRAIRIE', '{\"PR\", \"PRAIRIE\", \"PRR\"}', 'PR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RADIAL', '{\"RAD\", \"RADIAL\", \"RADIEL\", \"RADL\"}', 'RADL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RAMP', '{\"RAMP\"}', 'RAMP', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RANCH', '{\"RANCH\", \"RANCHES\", \"RNCH\", \"RNCHS\"}', 'RNCH', 'Fazenda', 'FZD');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RAPID', '{\"RAPID\", \"RPD\"}', 'RPD', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RAPIDS', '{\"RAPIDS\", \"RPDS\"}', 'RPDS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('REST', '{\"REST\", \"RST\"}', 'RST', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RIDGE', '{\"RDG\", \"RDGE\", \"RIDGE\"}', 'RDG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RIDGES', '{\"RDGS\", \"RIDGES\"}', 'RDGS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RIVER', '{\"RIV\", \"RIVER\", \"RVR\", \"RIVR\"}', 'RIV', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ROAD', '{\"RD\", \"ROAD\"}', 'RD', 'Estrada', 'ESTR');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ROADS', '{\"ROADS\", \"RDS\"}', 'RDS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ROUTE', '{\"ROUTE\"}', 'RTE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('ROW', '{\"ROW\"}', 'ROW', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RUE', '{\"RUE\"}', 'RUE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('RUN', '{\"RUN\"}', 'RUN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SHOAL', '{\"SHL\", \"SHOAL\"}', 'SHL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SHOALS', '{\"SHLS\", \"SHOALS\"}', 'SHLS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SHORE', '{\"SHOAR\", \"SHORE\", \"SHR\"}', 'SHR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SHORES', '{\"SHOARS\", \"SHORES\", \"SHRS\"}', 'SHRS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SKYWAY', '{\"SKYWAY\"}', 'SKWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SPRING', '{\"SPG\", \"SPNG\", \"SPRING\", \"SPRNG\"}', 'SPG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SPRINGS', '{\"SPGS\", \"SPNGS\", \"SPRINGS\", \"SPRNGS\"}', 'SPGS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SPUR', '{\"SPUR\"}', 'SPUR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SQUARE', '{\"SQ\", \"SQR\", \"SQRE\", \"SQU\", \"SQUARE\"}', 'SQ', 'Quadra', 'QD');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SQUARES', '{\"SQRS\", \"SQUARES\"}', 'SQS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('STATION', '{\"STA\", \"STATION\", \"STATN\", \"STN\"}', 'STA', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('STRAVENUE', '{\"STRA\", \"STRAV\", \"STRAVEN\", \"STRAVENUE\", \"STRAVN\", \"STRVN\", \"STRVNUE\"}', 'STRA', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('STREAM', '{\"STREAM\", \"STREME\", \"STRM\"}', 'STRM', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('STREET', '{\"STREET\", \"STRT\", \"ST\", \"STR\"}', 'ST', 'Rua', 'R');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('STREETS', '{\"STREETS\"}', 'STS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SUBDIVISION', '{\"SUBDIVISION\"}', 'SUBD', 'LOTEAMENTO', 'LT');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('SUMMIT', '{\"SMT\", \"SUMIT\", \"SUMITT\", \"SUMMIT\"}', 'SMT', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TERRACE', '{\"TER\", \"TERR\", \"TERRACE\"}', 'TER', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('THROUGHWAY', '{\"THROUGHWAY\"}', 'TRWY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TRACE', '{\"TRACE\", \"TRACES\", \"TRCE\"}', 'TRCE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TRACK', '{\"TRACK\", \"TRACKS\", \"TRAK\", \"TRK\", \"TRKS\"}', 'TRAK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TRAFFICWAY', '{\"TRAFFICWAY\"}', 'TRFY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TRAIL', '{\"TRAIL\", \"TRAILS\", \"TRL\", \"TRLS\"}', 'TRL', 'Trilha', 'Tlh');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TRAILER', '{\"TRAILER\", \"TRLR\", \"TRLRS\"}', 'TRLR', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TUNNEL', '{\"TUNEL\", \"TUNL\", \"TUNLS\", \"TUNNEL\", \"TUNNELS\", \"TUNNL\"}', 'TUNL', 'Túnel', 'TUN');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('TURNPIKE', '{\"TRNPK\", \"TURNPIKE\", \"TURNPK\"}', 'TPKE', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('UNDERPASS', '{\"UNDERPASS\"}', 'UPAS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('UNION', '{\"UN\", \"UNION\"}', 'UN', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('UNIONS', '{\"UNIONS\"}', 'UNS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VALLEY', '{\"VALLEY\", \"VALLY\", \"VLLY\", \"VLY\"}', 'VLY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VALLEYS', '{\"VALLEYS\", \"VLYS\"}', 'VLYS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VIADUCT', '{\"VDCT\", \"VIA\", \"VIADCT\", \"VIADUCT\"}', 'VIA', 'Viaduto', 'VD');
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VIEW', '{\"VIEW\", \"VW\"}', 'VW', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VIEWS', '{\"VIEWS\", \"VWS\"}', 'VWS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VILLAGE', '{\"VILL\", \"VILLAG\", \"VILLAGE\", \"VILLG\", \"VILLIAGE\", \"VLG\"}', 'VLG', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VILLAGES', '{\"VILLAGES\", \"VLGS\"}', 'VLGS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VILLE', '{\"VILLE\", \"VL\"}', 'VL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('VISTA', '{\"VIS\", \"VIST\", \"VISTA\", \"VST\", \"VSTA\"}', 'VIS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WALK', '{\"WALK\", \"WALKS\"}', 'WALK', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WALL', '{\"WALL\"}', 'WALL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WAY', '{\"WY\", \"WAY\"}', 'WAY', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WAYS', '{\"WAYS\"}', 'WAYS', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WELL', '{\"WELL\"}', 'WL', NULL, NULL);
INSERT INTO `address_suffix` (`suffix`, `common_abbrev`, `pss_abbrev`, `pt_br`, `abbrev_pt_br`) VALUES ('WELLS', '{\"WELLS\", \"WLS\"}', 'WLS', NULL, NULL);
